package com.wm.ob.emp.sm;

public enum EmployeeEvent {
    BEGIN_CHECK //`BEGIN CHECK`
    , FINISH_SECURITY_CHECK //`FINISH SECURITY CHECK`
    , COMPLETE_INITIAL_WORK_PERMIT_CHECK //`COMPLETE INITIAL WORK PERMIT CHECK`
    , FINISH_WORK_PERMIT_CHECK //`FINISH WORK PERMIT CHECK`
    , ACTIVATE //`ACTIVATE`
}
